app/blueprints/comp_timeline.py
from flask import Flask, Blueprint, request, session, g, redirect, url_for, abort, render_template, flash
from .models import get_db, User, POfficer
import datetime

comp_timeline = Blueprint('comp_timeline', __name__, static_url_path='/static');

@comp_timeline.route("/comp_timeline")
def timeline():

    student_id = session['user']['username']

    company = get_db().execute(
        '''SELECT calendar.comp_id, company.comp_name, calendar.date, calendar.purpose
        FROM calendar,company
        where calendar.comp_id = company.comp_id
        '''
        ).fetchall()

    registered = get_db().execute(
        '''SELECT comp_id
        FROM registered
        where registered.stud_id = ?
        ''', (student_id, )
        ).fetchall()
        
    company = [list(x) for x in company]
    company = sorted(company,key=lambda x: datetime.datetime.strptime(x[2], '%d-%m-%Y').date())
    registered = [x[0] for x in registered]

    # test data
    company = [
        ('C02',	'Tivo',	'13-08-2017', 'Online test'),
        ('C03',	'Infosys',	'14-08-2017', 'Interview'),
        ('C04',	'Play Simple',	'15-08-2017', 'Interview'),
        ('C05',	'Tetronix',	'16-08-2017', 'Online test')
    ]
    registered = ['C01', 'C02', 'C03']

    return render_template("comp_timeline.html", companies=company, registered=registered)

app/blueprints/messages.py
from flask import Flask, Blueprint, request, session, g, redirect, url_for, abort, render_template, flash
from .models import get_db, User, POfficer

messages = Blueprint('messages', __name__);



@messages.route('/history')
def history():
	db = get_db()
	cur = db.execute("SELECT * from postLog  where strftime('%d','now') - strftime('%d',LastPost) < 2 and stud_id =(?); ",[session.get('username'),])
	entries = cur.fetchall()
	return render_template('show_history.html',entries=entries)
	'''for entry in entries:
		print(entry[0],entry[1],entry[2],entry[3])
		sys.stdout.flush()	'''

@messages.route('/sendmessage',methods=['GET','POST'])
def sendmessage():
	
	if request.method == 'POST':
		print(" I am here in Post")
		sys.stdout.flush()
		if  session.get('logged_in'):
			print(" I am here session ")
			sys.stdout.flush()
			recipient = 'dishaatalreja@gmail.com'
			gmail_user = request.form['username']
			gmail_pwd = request.form['password']
			FROM = gmail_user
			TO = recipient if type(recipient) is list else [recipient]
			SUBJECT = request.form['subject']
			TEXT = request.form['body']
			message = """From: %s\nTo: %s\nSubject: %s\n\n%s""" % (FROM, ", ".join(TO), SUBJECT, TEXT)
			try:
				server = smtplib.SMTP("smtp.gmail.com", 587)
				server.ehlo()
				server.starttls()
				server.login(gmail_user, gmail_pwd)
				server.sendmail(FROM, TO, message)
				server.close()
				db = get_db()
				cur = db.execute("INSERT into postLog(stud_id,Message) VALUES (?,?);",[session.get('username'),request.form['body']])
				db.commit()
				flash('successfully sent the mail')
				sys.stdout.flush()
			except:
				flash("failed to send mail")
				sys.stdout.flush()
	
	return render_template('send_message.html')
			

app/blueprints/notification.py
from flask import Flask, Blueprint, request, session, g, redirect, url_for, abort, render_template, flash
from .models import get_db, User, POfficer

notification = Blueprint('notification', __name__);


@notification.route('/register/<comp_name>/')
def register(comp_name):
	print(comp_name)
	sys.stdout.flush()
	db = get_db()
	cur = db.execute('select * from Student where stud_id=(?);',[session.get('username'),])
	print("I am here")
	sys.stdout.flush()
	entries = cur.fetchall()
	f = open(comp_name+'.csv','r')
	line_no = 0
	registered = []
	for line in f:
		if line_no == 0:
			line_no = line_no+1
			continue
		registered.append(line.split(',')[0].strip())
		
	f.close()
	#print(registered)
	with open(comp_name+'.csv','a') as out:
		csv_out=csv.writer(out)
		for entry in entries :
			#csv_out.writerow(entry)
			l = []
			if entry[0] in registered:
				flash('You have already registered')
				return redirect(url_for('notifications'))
			else :
				for e in entry:
					l.append(e)
				print(tuple(l))
				csv_out.writerow(tuple(l))
				sys.stdout.flush()
			out.close()
	flash("you have successfully registred")
	return redirect(url_for('notifications'))

@notification.route('/information/<comp_name>/')
def information(comp_name):
	db = get_db()
	cur = db.execute('select c.comp_id,c.comp_name,c.address,c.description,c.sector,c.tier,c.contact,j.role,j.ctc,j.stipend,j.location from Company c,Job_Info j where c.comp_name=(?) and c.comp_id=j.comp_id;',[comp_name,])
	entries = cur.fetchall()
	return render_template('show_company_info.html', entries=entries)	

app/blueprints/profile.py
from flask import Flask, Blueprint, request, session, g, redirect, url_for, abort, render_template, flash
from .models import get_db, User, POfficer
from .views import views

profile = Blueprint('profile', __name__, template_folder="/template");



@profile.route("/edit")
def profile_edit():
	if session.get('logged_in'):
		return render_template('profile_edit.html')
	return redirect(url_for('views.index'))

@profile.route("/save", methods=['GET', 'POST'])
def profile_save():
	if request.method == 'POST' and session.get('logged_in'):
		print("hi")
		db = get_db()
		data = request.form
		to_db = [data['name'], data['cgpa'], data['sec_cgpa'], data['prim_cgpa'], data['contact'], data['email'], data['backlogs'], data['dept']]
		print(session['user'])
		cur = db.execute('select * from Student where stud_id=(?);',[session['user']['username']])
		entry = cur.fetchall()[0]
		to_db = [entry[0]] + to_db + [entry[9]]
		db.execute('DELETE FROM Student where stud_id=(?)', [entry[0]])
		db.execute("INSERT INTO Student(stud_id,name,cgpa,sec_cgpa,prim_cgpa,contact,email,backlogs,dept,password) VALUES (?,?,?,?,?,?,?,?,?,?);",tuple(to_db))
		db.commit();
		session['user'] = User(to_db).__dict__
		return redirect(url_for('views.profile'));
	return redirect(url_for('views.index'));

@profile.route("/change", methods=['GET', 'POST'])
def change_password():
	if request.method == 'POST' and session.get('logged_in'):
		db = get_db()
		data = session['user']
		opasswd = request.form['opasswd']
		npasswd = request.form['npasswd']
		to_db = [data['username'], data['name'], data['cgpa'], data['sec_cgpa'], data['prim_cgpa'], data['contact'], data['email'], data['backlogs'], data['dept']]
		cur = db.execute('select * from Student where stud_id=(?);',[session['user']['username']])
		entry = cur.fetchall()[0]
		type(entry)
		if opasswd == entry[9]:
			to_db.append(npasswd)
			db.execute('DELETE FROM Student where stud_id=(?)', [entry[0]])
			db.execute("INSERT INTO Student(stud_id,name,cgpa,sec_cgpa,prim_cgpa,contact,email,backlogs,dept,password) VALUES (?,?,?,?,?,?,?,?,?,?);",tuple(to_db))
			db.commit()
			session['user'] = User(to_db).__dict__
		else:
			return redirect(url_for('views.profile'))

	return redirect(url_for('views.profile'))

app/blueprints/views.py
from flask import Flask, Blueprint, request, session, g, redirect, url_for, abort, render_template, flash
from .models import get_db, User, POfficer

views = Blueprint('views', __name__);

@views.route("/")
def index():
	return render_template("index.html");

@views.route("/home")
def home():
	if not session.get('logged_in'):
		return redirect(url_for('views.login'));
	session['userprofile_pic'] = "/static/assets/images/rain-dp.jpg";
	return render_template("notifications.html")

@views.route('/signup', methods=['GET', 'POST'])
def signup():
	db = get_db()
	message = None
	if request.method == "POST" and not session.get('logged_in'):
		cur = db.execute('select * from Student where stud_id=(?) or email=(?);',[request.form['username'], request.form['email']])
		entries = cur.fetchall()
		if len(entries) > 0:
			message = "username or Email id already registered"
		else:
			data = request.form
			to_db = [data['username'], data['name'], data['cgpa'], data['sec_cgpa'], data['prim_cgpa'], data['contact'], data['email'], data['backlogs'], data['dept'], data['password']]
			print("new_1")
			db.execute("INSERT INTO Student(stud_id,name,cgpa,sec_cgpa,prim_cgpa,contact,email,backlogs,dept,password) VALUES (?,?,?,?,?,?,?,?,?,?);",tuple(to_db))
			db.commit();
			session['logged_in'] = True
			flash('You were signed up')
			session['user'] = User(to_db[:-1]).__dict__
			return render_template('home.html', message="You have successfully signed up.")

	if session.get('logged_in'):
		return redirect(url_for('views.home'));

	return render_template('signup.html', message=message);

@views.route('/login', methods=['GET', 'POST'])
def login():
	message = None
	db = get_db()
	if request.method == 'POST' and not session.get('logged_in'):
		db = get_db()
		cur = db.execute('select * from Student where stud_id=(?);',[request.form['username'],])
		entries = cur.fetchall()
		for entry in entries:
			if entry[9] == request.form['password']:
				session['logged_in'] = True
				flash('You were logged in')
				session['user']= User(list(entry)[:-1]).__dict__
				return redirect(url_for('views.home'))
			else :
				return render_template('login.html', message="Invalid password")
		else :
			error = "Invalid username"

	if session.get('logged_in'):
		return redirect(url_for('views.home'));
	return render_template('login.html', message=message)

@views.route('/logout')
def logout():
	session.pop('logged_in', None)
	session.pop('username',None)
	flash('You were logged out')
	return redirect(url_for('views.login'))


@views.route("/profile")
def profile():
	return render_template("profile.html")


@views.route("/notifications")
def notifications():
	return render_template("notifications.html")


@views.route("/messages")
def messages():
	return render_template("messages.html")


@views.route("/comp_timeline")
def comp_timeline():
	return render_template("comp_timeline.html")

app/templates/comp_timeline.html
{%- extends "home.html" %}
{%- block content %}

	<div class="jumbotron">
		{%for company in companies%}
		<center>
			<div class="well">
				{%if company[0] in registered%}
					<h2>{{company[1]}}</h2><h3>{{company[3]}} on {{company[2]}} 
					</h3><h6 style="color:green">Registered!</h6>
				{%else%}
					<h2>{{company[1]}}</h2><h3>{{company[3]}} on {{company[2]}} 
				{%endif%}
			</h3></div>
		</center>
		{%endfor%}
	</div>

	<script>
		$(".sidebar a").removeClass("active");
		$("#comp_timeline").addClass("active");
	</script>
{%- endblock %}

app/templates/home.html
{%- extends "base.html" %}

{%- block title %}{{ 'Home - ' + session['user'].name  }}{% endblock %}
  
{%- block menu_action %}
  <a href="#" id="menu-action">
   <i class="fa fa-bars"></i>
   <span>Close</span>
  </a>
{%- endblock %}
{%- block dropdown %}   	
   	<div class="dropdown pull-right">
       <a class="dropdown-toggle dd" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
        <!-- The Profile picture inserted via div class below, with shaping provided by Bootstrap -->
        <div class="img-profile"><span>{{ session['user'].name }}</span><img class = "dp-icon img-circle" src = "/static/assets/images/rain-dp.jpg">
      	<span class="fa fa-angle-down white"></span>
      	</div>
       </a>
      <ul class="dropdown-menu">
          <li>
            <a href="{{ url_for('views.profile') }}">Profile</a>
          </li>
          <li role="separator" class="divider"></li>
          <li>
             <a href="{{ url_for('views.logout') }}">Log out</a>
           </li>
      </ul>
   </div>
{%- endblock %}
{%- block sidebar %}
<div class="sidebar">
  <ul>
    <li><a id="notifications" href="{{ url_for('views.notifications') }}"><i class="fa fa-bell"></i><span>Notifications</span></a></li>

    <!-- test -->
    <li><a id="messages" href="{{ url_for('views.messages') }}"> <i class="fa fa-envelope"></i><span >Messages</span></a></li>
    <!-- <li><a id="messages" onclick="alert('okok');" ></a> <i class="fa fa-envelope"></i><span>Messages</span></a></li> -->

    <li><a id="comp_timeline" href="{{ url_for('views.comp_timeline') }}"><i class="fa fa-briefcase"></i><span>Company Timeline</span></a></li>
</div>
{%- endblock %}

app/templates/index.html
{% extends "base.html" %}
{%- block styles %}
    <link href="static/styles/index.css" rel="stylesheet">
{%- endblock %}

{%- block body %}
    <!-- Navigation -->
    <nav id="siteNav" class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Logo and responsive toggle -->
            <a id = "logo" class = "navbar-brand" href = "{% if session.get('logged_in') %} {{ url_for('views.home') }}  {% else %} {{ url_for('views.index')}} {% endif %}">
                <img class ="icon-logo" src="static/assets/icons/pes_logo.png" alt = ""/> <span>PES Placements</span>
            </a>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <!-- Navbar links -->
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="nav navbar-nav navbar-right">
                    <li class="active">
                        <a href="#">Home</a>
                    </li>
                    <li>
                        <a href="{{ url_for('views.login') }}">Login</a>
                    </li>
                    <li>
                        <a href="{{ url_for('views.signup') }}">Signup</a>
                    </li>
                </ul>
                
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>

	<!-- Header -->
    <header style="background:#1677C4">
        <div class="header-content">
            <div class="header-content-inner">
                <h1>PES Placements Portal</h1>
                <p>A Platform to manage all your campus placements</p>
                <a href="{{ url_for('views.signup')}}" class="btn btn-primary btn-lg" style="background:#1E346D">Signup Now</a>
            </div>
        </div>
    </header>

	<!-- Intro Section -->
    <section class="intro" style="background:#3498DB">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                	
                    <h2 class="section-heading">Completely organize your placements</h2>
                    <p class="text-light">Get information on the upcoming activity in placements in PES University anytime, 
                    anywhere. Managing campus placements is not easy. We get that. That's why we built a platform to take care of all your 
                    needs. Get rid of countless Excel sheets, keep students up-to-date and get instant reports and focus on what matters. 
                    Spend time on guiding students and building company relations. Get email notifications to a specific set of students. 
                    Alerts and reminders are automatically sent to all concerned students when any deadline approaches.</p>
                </div>
            </div>
        </div>
    </section>

	<!-- Content 1 -->
    <!--<section class="content" style="background:#1677C4">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                	<h3 class="text-light">About</h3>
                	<p class="lead text-muted"></p>
                </div>                   
            </div>
        </div>
    </section>-->
    
	<!-- Footer -->
    <footer class="page-footer">
    
    	<!-- Contact Us -->
        <div class="contact" style="background:#1677C4">
        	<div class="container">
				<h2 class="section-heading">Contact Us</h2>
				<p><span class="glyphicon glyphicon-earphone"></span><br> +91 9xxxxxxxxx</p>
				<p><span class="glyphicon glyphicon-envelope"></span><br> info@pesplacements.com</p>
        	</div>
        </div>
        	
        <!-- Copyright etc -->
        <div class="small-print">
       		<p>Copyright </p>
        </div>
        
    </footer>
    <!-- Custom Javascript -->
    <script src="static/js/index.js"></script>

{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{%- block title %} Login / Signup - PES Placements {%- endblock %} 
{%- block styles %}
	<link href="{{url_for('static', filename='styles/login.css')}}" rel="stylesheet" />
{%- endblock %}

{%- block content %}
 <div class= "row">
  <div class="form">
      
      <ul class="tab-group" >
        <li class="tab"><a>Sign Up</a></li>
        <li class="tab active"><a >Log In</a></li>
      </ul>
      
      <div class="tab-content">
        <div id="signup" class ="hidden">   
          <h1>Sign Up</h1>
          
          <form action="{{ url_for('views.signup') }}" method=post>
          
          
          <div class="field-wrap">
              <input type="text" required name="username" maxlength="20" class = "inp-element" autocomplete="off" placeholder=" Username*"/>
          </div>

          <div class="field-wrap">
              <input type="text" name="name" maxlength="60" class = "inp-element" required autocomplete="off" placeholder=" Full Name*"/>
          </div>

          <div class="field-wrap">
            <input type="email"required name="email" class = "inp-element" autocomplete="off" placeholder=" Email Address*"/>
          </div>
          
          <div class="field-wrap">

            <input type="password"required name="password" class = "inp-element" autocomplete="off" placeholder=" Password*"  />
          </div>

          <div class="field-wrap">
              <input type="number" required name="cgpa" step = "0.01" step = "0.1" max="10" min="0" class = "inp-element" autocomplete="off" placeholder=" CGPA*"/>
          </div>

          <div class="field-wrap">
              <input type="number" required name="sec_cgpa" step = "0.01" class = "inp-element" autocomplete="off" placeholder=" PU/XII CGPA*"/>
          </div>


          <div class="field-wrap">
              <input type="number" required name="prim_cgpa" step = "0.01" max="10" min="0" class = "inp-element" autocomplete="off" placeholder=" X CGPA*"/>
          </div>

          <div class="field-wrap">
              <input type="text" required name="contact" minlength="10" maxlength="10" class = "inp-element" autocomplete="off" placeholder=" Contact No.*"/>
          </div>

          <div class="field-wrap">
              <input type="number" required name="backlogs"  step="1" min = "0" max="5" class = "inp-element" autocomplete="off" placeholder="No. of backlogs*"/>
          </div>

          <div class="field-wrap">
              <select name="dept" required>
                <option value="">Choose Department</option>
                <option value="CS">Computer Science Engineering</option>
                <option value="IS">Information Science Engineering</option>
                <option value="ME">Mechanical Engineering</option>
                <option value="EEE">Electrical Engineering</option>
                <option value="EC">Electronic Engineering</option>
              </select>
          </div>
          
          <input type="submit" class="button button-block inp-element" Value="Get Started" style="background-color: #3498DB;"/>
          </form>

        </div>
        
        <div id="login" class="visible">   
          <h1>Welcome Back!</h1>
          
          <form action="{{ url_for('views.login') }}" method=post>
          
            <div class="field-wrap">
            <input type="username" name=username required class = "inp-element" autocomplete="off" placeholder="Username*" />
          </div>

          <div class="field-wrap">
            <input type="password"required name=password class = "inp-element" autocomplete="off" placeholder="Password*"  />
          </div>
          
          <!--p class="forgot"><a href="#">Forgot Password?</a></p-->
          
          <input type="submit" class="button button-block inp-element" value="Log In" style="background-color: #3498DB;" />
          
          </form>

        </div>
        
      </div><!-- tab-content -->
      
	</div> <!-- /form -->
	</div>
	{% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}</p>
</div>

{%- endblock %}

app/templates/messages.html
{%- extends "home.html" %}
{%- block content %}
	<script>
		$(".sidebar a").removeClass("active");
		$("#messages").addClass("active");
	</script>
{%- endblock %}

app/templates/profile.html
{%- extends "home.html" %}
{%- block styles %}
{%- endblock %}
{%- block content %}
<div class="main">
  <div class="hipsum">
	<div class="jumbotron">
		<div class="container">
			<div class="row top-bottom-buffer">
				<div class="col-sm-10 col-sm-offset-1 col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 text-center"><h1 class="page-header profile-heading"> Profile</h1>
				 </div>
			</div>
			<div class="row bottom-buffer">
				<div class = "table-content">
				<table class="table text-centered table-layout">
				<tr>
					<td class="left-column">
						Full &nbsp Name
					</td>
					<td class = "center-column">
						:
					</td>
					<td class = "right-column">
						<span id="name" class="profile-data">{{session['user'].name}}</span>
					</td>
				</tr>
				<tr>
					<td class="left-column">
						Department
					</td>
					<td class = "center-column">
						:
					</td>
					<td class = "right-column">
						<span id="dept" class="profile-data">{{session['user'].dept}}</span>
					</td>
				</tr>
				<tr>
					<td class="left-column">
						CGPA
					</td>
					<td>
						:
					</td>
					<td class = "right-column">
						<span id="cgpa" class="profile-data">{{session['user'].cgpa}}</span>
					</td>
				</tr>
				<tr>
					<td class="left-column">
						PU &nbsp CGPA
					</td>
					<td>
						:
					</td>
					<td class = "right-column">
						<span id="sec_cgpa" class="profile-data">{{session['user'].sec_cgpa}}</span>
					</td>
				</tr>
				<tr>
					<td class="left-column">
						X &nbsp CGPA
					</td>
					<td class = "center-column">
						:
					</td>
					<td class = "right-column">
						<span id="prim_cgpa" class="profile-data">{{session['user'].prim_cgpa}}</span>
					</td>
				</tr>
				<tr>
					<td class="left-column">
						Backlogs
					</td>
					<td class = "center-column">
						:
					</td>
					<td class = "right-column">
						<span id="backlogs" class="profile-data">{{session['user'].backlogs}}</span>
					</td>
				</tr>
				</table>
				</div>
			</div>
			<div class="row top-bottom-buffer">
				<div class="col-sm-10 col-sm-offset-1 col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 text-center"><h1 class="page-header profile-heading"> Account</h1></div>
			</div>
			<div class="row bottom-buffer">
				<div class = "table-content">
					<table class="table text-centered table-layout">
				<tr>
					<td class="left-column">
						Username
					</td>
					<td class = "center-column">
						:
					</td>
					<td class = "right-column">
						<span id="username" value="{{ session['user'].username }}"class="account-data">{{ session['user'].username }}</span>
					</td>
				</tr>
				<tr>
					<td class="left-column">
						Email Id
					</td>
					<td class = "center-column">
						:
					</td>
					<td class = "right-column">
						<span id="email" value="{{ session['user'].email }}" class="account-data editable">{{session['user'].email}}</span>
					</td>
				</tr>
				<tr>
					<td class="left-column">
						Contact No
					</td>
					<td class = "center-column">
						:
					</td>
					<td class = "right-column">
						<span id="contact" value="{{ session['user'].contact }}" class="account-data editable">{{session['user'].contact}}</span>
					</td>
				</tr>
				</table>
				</div>
				<form action="{{ url_for('profile.profile_edit') }}" method="get">
					<input  type="submit" id ="profile-edit" value="Edit" class="save btn btn-primary edit-btn"/>
				</form>
			</div>
			<div class="row top-bottom-buffer">
				<div class="col-sm-10 col-sm-offset-1 col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 text-center"><h1 class="page-header profile-heading"> Change Password</h1></div>
			</div>
			<div class="row bottom-buffer">
				<div class = "table-content">
				<form action="{{ url_for('profile.change_password')}}" method="post">
				<table class="table text-centered table-layout">
				<tr>
					<td class="left-column">
						Old &nbsp Password
					</td>
					<td class = "center-column">
						:
					</td>
					<td class = "right-column">
						<input type="password" id="opasswd" name="opasswd" class="password-data" />
					</td>
				</tr>
				<tr>
					<td class="left-column">
						New &nbsp Password
					</td>
					<td class = "center-column">
						:
					</td>
					<td class = "right-column">
						<input type="password" id="npasswd" name="npasswd" class="password-data" />
					</td>
				</tr>
				</table>
					<input  type="submit" id ="change-passwd" value="Change" class="btn btn-primary edit-btn"/>
				</form>
				</div>
			</div>
			
		</div>
	  </div>
	</div>
</div>
{%- endblock %}

app/templates/profile_edit.html
{%- extends "home.html" %}
{%- block styles %}
{%- endblock %}
{%- block content %}
<div class="main">
  <div class="hipsum">
	<div class="jumbotron">
		<div class="container">
			<form action="{{ url_for('profile.profile_save')}}" method="post">
			<div class="row top-bottom-buffer">
				<div class="col-sm-10 col-sm-offset-1 col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 text-center"><h1 class="page-header profile-heading"> Profile</h1>
				 </div>
			</div>
			
			<div class="row bottom-buffer">
				<div class = "table-content">
				<table class="table text-centered table-layout">
				<tr>
					<td class="left-column">
						Full &nbsp Name
					</td>
					<td class = "center-column">
						:
					</td>
					<td class = "right-column">
						<input type="text" required name="name" maxlength="60" class = "inp-element" autocomplete="off" value="{{ session['user'].name}}"/>
					</td>
				</tr>
				<tr>
					<td class="left-column">
						Department
					</td>
					<td class = "center-column">
						:
					</td>
					<td class = "right-column">
						<div class="field-wrap">
			              <select id = "dept" name="dept" required>
			                <option value="">Choose Department</option>
			                <option id="CS" value="CS">Computer Science Engineering</option>
			                <option id="IS" value="IS">Information Science Engineering</option>
			                <option id="ME" value="ME">Mechanical Engineering</option>
			                <option id="EEE" value="EEE">Electrical Engineering</option>
			                <option id="EC" value="EC">Electronic Engineering</option>
			              </select>
			          </div>
					</td>
				</tr>
				<tr>
					<td class="left-column">
						CGPA
					</td>
					<td>
						:
					</td>
					<td class = "right-column">
						 <input type="number" required name="cgpa" step = "0.01" step = "0.1" max="10" min="0" class = "inp-element" autocomplete="off" value="{{ session['user'].cgpa }}"/>
					</td>
				</tr>
				<tr>
					<td class="left-column">
						PU &nbsp CGPA
					</td>
					<td>
						:
					</td>
					<td class = "right-column">
						 <input type="number" required name="sec_cgpa" step = "0.01" class = "inp-element" autocomplete="off" value="{{session['user'].sec_cgpa}}"/>
					</td>
				</tr>
				<tr>
					<td class="left-column">
						X &nbsp CGPA
					</td>
					<td class = "center-column">
						:
					</td>
					<td class = "right-column">
						<input type="number" required name="prim_cgpa" step = "0.01" max="10" min="0" class = "inp-element" autocomplete="off" value="{{session['user'].prim_cgpa}}"/>
					</td>
				</tr>
				<tr>
					<td class="left-column">
						Backlogs
					</td>
					<td class = "center-column">
						:
					</td>
					<td class = "right-column">
						<input type="number" required name="backlogs"  step="1" min = "0" max="5" class = "inp-element" autocomplete="off" value="{{session['user'].backlogs}}"/>
					</td>
				</tr>
				</table>
				</div>
			</div>
			<div class="row top-bottom-buffer">
				<div class="col-sm-10 col-sm-offset-1 col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 text-center"><h1 class="page-header profile-heading"> Account</h1></div>
			</div>
			<div class="row bottom-buffer">
				<div class = "table-content">
				<table class="table text-centered table-layout">
				<tr>
					<td class="left-column">
						Username
					</td>
					<td class = "center-column">
						:
					</td>
					<td class = "right-column">
						<span id="username" class="account-data">{{ session['user'].username }}</span>
					</td>
				</tr>
				<tr>
					<td class="left-column">
						Email Id
					</td>
					<td class = "center-column">
						:
					</td>
					<td class = "right-column">
						<input type="email"required name="email" class = "inp-element" autocomplete="off" value="{{session['user'].email}}"/>
					</td>
				</tr>
				<tr>
					<td class="left-column">
						Contact No
					</td>
					<td class = "center-column">
						:
					</td>
					<td class = "right-column">
						<input type="text" required name="contact" minlength="10" maxlength="10" class = "inp-element" autocomplete="off" value="{{session['user'].contact}}"/>
					</td>
				</tr>
				</table>
				</div>
				<input  type="submit" id ="profile-edit" value="Save" class="save btn btn-primary edit-btn"/>
			</form>
		 	</div>	
		</div>
	  </div>
	</div>
</div>
	<script>
		$("select option[value='{{session['user'].dept}}']").attr("selected","selected");
	</script>
{%- endblock %}